name: mobile1
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  retrofit: ^2.0.0
  dio: ^4.0.0
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  retrofit_generator: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.mobile1
    iosBundleIdentifier: com.example.mobile1
